import React from 'react';
import { z } from 'zod';
import { Ch1Stage, CH1, SERIF, SANS, MONO, cue, clamp, useBeatProgress } from './Ch1Chrome';

/**
 * Ch1PretrainLadder — Act 2. The softmax, one column at a time.
 *
 * ONE component renders all five steps, driven by `step` (1..5). Each beat in
 * the act shows the same four tokens with exactly one more column revealed,
 * so a viewer who has never seen a logit is never asked to absorb two new
 * things at once — and the columns they already understand stay on screen as
 * the ground the next one is built on.
 *
 * Step 2 (subtract the max) is in here because it is what real
 * implementations do: exp(z) overflows for large z, and
 * exp(z-m)/Σexp(z-m) = exp(z)/Σexp(z) exactly. Showing the naive form would
 * be showing something nobody runs.
 *
 * Every figure is generated by verify_softmax.py --emit into
 * softmax_values.json and injected into the beat sheet, so nothing here is
 * hand-typed.
 */

export const ch1PretrainLadderSchema = z.object({
  durationS: z.number().default(20),
  /** 1 = logits · 2 = subtract max · 3 = exponentiate · 4 = normalize · 5 = probabilities */
  step: z.number().int().min(1).max(5).default(1),
  sparkLine: z.string().default('One step at a time.'),
  /** Plain-language sentence for the step being introduced. */
  stepNote: z.string().default(''),
  vocab: z.array(z.string()).default(['rock', 'cheese', 'gas', 'light']),
  logits: z.array(z.number()).default([4.0, 1.0, 0.0, -0.5]),
  maxValue: z.number().default(4.0),
  shifted: z.array(z.number()).default([0.0, -3.0, -4.0, -4.5]),
  exps: z.array(z.number()).default([1.0, 0.0498, 0.0183, 0.0111]),
  expSum: z.number().default(1.0792),
  probs: z.array(z.number()).default([0.9266, 0.0461, 0.017, 0.0103]),
  pct: z.array(z.number()).default([92.7, 4.6, 1.7, 1.0]),
  target: z.string().default('cheese'),
});
export type Ch1PretrainLadderProps = z.infer<typeof ch1PretrainLadderSchema>;

const COL = { token: 250, z: 150, shift: 200, exp: 200, div: 380, p: 190, pct: 150 } as const;
const GAP = 26;

const STEP_LABEL = [
  '',
  'RAW SCORES',
  'SUBTRACT THE MAX',
  'EXPONENTIATE',
  'DIVIDE BY THE SUM',
  'THE PROBABILITIES',
];

const Head: React.FC<{ w: number; text: string; live: boolean; right?: boolean; show: number }> =
  ({ w, text, live, right = false, show }) => (
    <div
      style={{
        width: w,
        fontFamily: SANS,
        fontSize: 20,
        fontWeight: 800,
        letterSpacing: '0.11em',
        color: live ? CH1.SPARK : CH1.INK_SOFT,
        textAlign: right ? 'right' : 'left',
        opacity: show,
        whiteSpace: 'nowrap',
      }}
    >
      {text}
    </div>
  );

export const Ch1PretrainLadder: React.FC<Ch1PretrainLadderProps> = (props) => {
  const p = useBeatProgress();
  const {
    step, sparkLine, stepNote, vocab, logits, maxValue, shifted, exps, expSum,
    probs, pct, target,
  } = ch1PretrainLadderSchema.parse(props);

  // Columns already established appear immediately (they are the ground the
  // viewer arrived with); the NEW column animates in on the spoken word.
  const settled = 1;
  const fresh = cue(p, 0.16, 0.34);
  const colShow = (n: number) => (n < step ? settled : n === step ? fresh : 0);
  const noteO = cue(p, 0.40, 0.56);
  const sumO = cue(p, 0.52, 0.68);
  const barO = cue(p, 0.62, 0.74);
  const barFill = cue(p, 0.66, 0.88);

  const STACK_W = 1650;

  return (
    <Ch1Stage sparkLine={sparkLine} sparkPos="top" banner="CONSTRUCTED EXAMPLE">
      <div style={{ display: 'flex', flexDirection: 'column', gap: 22 }}>
        {/* ── step counter + the step's own name ── */}
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 22 }}>
          <span style={{ fontFamily: SANS, fontSize: 22, fontWeight: 800, letterSpacing: '0.14em', color: CH1.INK_SOFT }}>
            STEP {step} OF 5
          </span>
          <span style={{ fontFamily: SERIF, fontSize: 46, fontWeight: 700, color: CH1.SPARK, letterSpacing: '-0.01em' }}>
            {STEP_LABEL[step]}
          </span>
          {step === 2 ? (
            <span style={{ fontFamily: MONO, fontSize: 28, color: CH1.INK_SOFT }}>
              max = {maxValue.toFixed(1)}
            </span>
          ) : null}
          {step >= 4 ? (
            <span style={{ fontFamily: MONO, fontSize: 28, color: CH1.INK_SOFT }}>
              Σ = {expSum.toFixed(4)}
            </span>
          ) : null}
        </div>

        {/* ── headers ── */}
        <div style={{ display: 'flex', gap: GAP, alignItems: 'flex-end' }}>
          <Head w={COL.token} text="CANDIDATE" live={false} show={1} />
          <Head w={COL.z} text="z" live={step === 1} right show={colShow(1)} />
          <Head w={COL.shift} text="z − max" live={step === 2} right show={colShow(2)} />
          <Head w={COL.exp} text="exp(z − max)" live={step === 3} right show={colShow(3)} />
          <Head w={COL.div} text="÷ Σ" live={step === 4} show={colShow(4)} />
          <Head w={COL.p} text="p" live={step === 5} right show={colShow(5)} />
          <Head w={COL.pct} text="PERCENT" live={step === 5} right show={colShow(5)} />
        </div>

        {/* ── rows ── */}
        {vocab.map((tok, i) => {
          const isTarget = tok === target;
          const rowIn = cue(p, 0.06 + i * 0.03, 0.18 + i * 0.03);
          const cell = (w: number, text: string, show: number, live: boolean, right = true, size = 40) => (
            <div
              style={{
                width: w,
                fontFamily: MONO,
                fontSize: size,
                fontWeight: live ? 700 : 500,
                color: live ? CH1.INK : CH1.INK_SOFT,
                textAlign: right ? 'right' : 'left',
                opacity: show < 1 ? show : live ? 1 : 0.62,
                whiteSpace: 'nowrap',
              }}
            >
              {text}
            </div>
          );
          return (
            <div key={tok} style={{ display: 'flex', gap: GAP, alignItems: 'center', opacity: rowIn }}>
              <div
                style={{
                  width: COL.token,
                  fontFamily: MONO,
                  fontSize: 44,
                  fontWeight: isTarget ? 700 : 500,
                  color: isTarget ? CH1.SPARK : CH1.INK,
                }}
              >
                {tok}
              </div>
              {cell(COL.z, `${logits[i] > 0 ? '+' : ''}${logits[i].toFixed(1)}`, colShow(1), step === 1)}
              {cell(COL.shift, shifted[i].toFixed(1), colShow(2), step === 2)}
              {cell(COL.exp, exps[i].toFixed(4), colShow(3), step === 3)}
              {cell(COL.div, `${exps[i].toFixed(4)} ÷ ${expSum.toFixed(4)}`, colShow(4), step === 4, false, 32)}
              {cell(COL.p, probs[i].toFixed(4), colShow(5), step === 5)}
              {cell(COL.pct, `${pct[i].toFixed(1)}%`, colShow(5), step === 5)}
            </div>
          );
        })}

        {/* ── the running total, once there is one ── */}
        {step >= 3 ? (
          <div
            style={{
              display: 'flex',
              gap: GAP,
              alignItems: 'center',
              opacity: step === 3 ? sumO : 1,
              borderTop: `3px solid ${CH1.INK}`,
              paddingTop: 18,
            }}
          >
            <div style={{ width: COL.token + COL.z + COL.shift + GAP * 2, fontFamily: SERIF, fontSize: 36, fontWeight: 700, color: CH1.INK }}>
              {step >= 5 ? 'Σ p' : 'Σ exp'}
            </div>
            <div style={{ width: COL.exp, fontFamily: MONO, fontSize: 40, fontWeight: 700, color: CH1.INK, textAlign: 'right' }}>
              {step >= 5 ? '' : expSum.toFixed(4)}
            </div>
            <div style={{ width: COL.div, fontFamily: SANS, fontSize: 23, color: CH1.INK_SOFT }}>
              {step === 3 ? 'the number everything is divided by'
                : step === 4 ? 'every row shares one denominator'
                : 'no mass left over — exactly'}
            </div>
            <div style={{ width: COL.p, fontFamily: MONO, fontSize: 44, fontWeight: 700, color: CH1.INK, textAlign: 'right' }}>
              {step >= 5 ? probs.reduce((a, b) => a + b, 0).toFixed(4) : ''}
            </div>
            <div style={{ width: COL.pct, fontFamily: MONO, fontSize: 40, fontWeight: 700, color: CH1.INK, textAlign: 'right' }}>
              {step >= 5 ? `${pct.reduce((a, b) => a + b, 0).toFixed(1)}%` : ''}
            </div>
          </div>
        ) : null}

        {/* ── the unit bar: the payoff, only at step 5 ── */}
        {step >= 5 ? (
          <div style={{ opacity: barO }}>
            <div style={{ display: 'flex', width: STACK_W, height: 62, borderRadius: 5, overflow: 'hidden', border: `3px solid ${CH1.INK}` }}>
              {vocab.map((tok, i) => {
                const isTarget = tok === target;
                const w = probs[i] * STACK_W * barFill;
                return (
                  <div
                    key={tok}
                    style={{
                      width: w,
                      height: '100%',
                      background: isTarget ? CH1.SPARK : CH1.INK,
                      opacity: isTarget ? 1 : 0.78,
                      borderRight: `2px solid ${CH1.GROUND}`,
                      display: 'flex',
                      alignItems: 'center',
                      paddingLeft: 14,
                      boxSizing: 'border-box',
                      overflow: 'hidden',
                    }}
                  >
                    <span style={{ fontFamily: MONO, fontSize: 25, color: CH1.CARD, whiteSpace: 'nowrap', fontWeight: 700 }}>
                      {w > 180 ? tok : ''}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        ) : null}

        {/* ── the plain-language note for this step ── */}
        {stepNote ? (
          <div
            style={{
              opacity: noteO,
              fontFamily: SERIF,
              fontSize: 38,
              color: CH1.INK,
              lineHeight: 1.32,
              maxWidth: 1660,
              fontWeight: 600,
            }}
          >
            {stepNote}
          </div>
        ) : null}
      </div>
    </Ch1Stage>
  );
};

export const ch1PretrainLadderDemoDefaultProps: Ch1PretrainLadderProps =
  ch1PretrainLadderSchema.parse({});
